/* Deep Sea Diver: Remastered — world-anchored biome scenery */
(function(){
  'use strict';
  var stage=document.getElementById('stage'); if(!stage) return;
  var D=window.GAMEDATA;
  var c=document.createElement('canvas'); c.id='remaster-scenery'; c.setAttribute('aria-hidden','true'); stage.appendChild(c);
  var g=c.getContext('2d'),dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));
  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function size(){var w=stage.clientWidth||innerWidth,h=stage.clientHeight||innerHeight,rw=Math.floor(w*dpr),rh=Math.floor(h*dpr);if(c.width!==rw||c.height!==rh){c.width=rw;c.height=rh;c.style.width=w+'px';c.style.height=h+'px';g.setTransform(dpr,0,0,dpr,0,0);}}
  function camera(run,state,w,h){var loc=run.loc||D.LOCATIONS[run.area];var skyReveal=(state&&state.items&&state.items.rocfeather&&run.diver.y<120)?-470:(run.diver.y<80?-290:-150);return{x:Math.round(clamp(run.diver.x-w/2,0,Math.max(0,loc.worldWidth-w))),y:Math.round(clamp(run.diver.y-h/2,skyReveal,Math.max(0,loc.maxDepth*D.PXPM+120-h)))};}
  function line(x1,y1,x2,y2,a,col,w){g.strokeStyle='rgba('+col+','+a+')';g.lineWidth=w||2;g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.stroke();}
  function worldX(loc,frac,cam){return loc.worldWidth*frac-cam.x;}
  function floorY(loc,cam){return loc.maxDepth*D.PXPM-cam.y;}
  function onScreen(x,y,w,h,pad){pad=pad||120;return x>-pad&&x<w+pad&&y>-pad&&y<h+pad;}

  function coral(loc,cam,w,h,t,col){var fy=floorY(loc,cam);g.save();for(var i=0;i<14;i++){var x=worldX(loc,.035+i*.071,cam),hh=38+(i%4)*18;if(!onScreen(x,fy,w,h,90))continue;var sway=Math.sin(t*.0012+i)*3;line(x,fy,x+sway,fy-hh,.12,col,5);line(x+sway*.55,fy-hh*.52,x-12+sway,fy-hh*.77,.09,col,3);line(x+sway*.42,fy-hh*.38,x+14+sway,fy-hh*.66,.09,col,3);}g.restore();}
  function kelp(loc,cam,w,h,t,col){var fy=floorY(loc,cam);g.save();g.strokeStyle='rgba('+col+',.12)';g.lineWidth=7;for(var i=0;i<18;i++){var wx=loc.worldWidth*(.02+i*.057),x=wx-cam.x;if(x<-60||x>w+60)continue;var ht=150+(i%5)*38;g.beginPath();g.moveTo(x,fy);for(var yy=0;yy<ht;yy+=26){var wy=fy-yy;g.lineTo(x+Math.sin(t*.0014+yy*.018+i)*9,wy);}g.stroke();}g.restore();}
  function reeds(loc,cam,w,h,t,col){var fy=floorY(loc,cam);g.save();for(var i=0;i<26;i++){var x=worldX(loc,.018+i*.039,cam);if(x<-20||x>w+20)continue;var ht=70+(i%6)*13,s=Math.sin(t*.0016+i)*5;line(x,fy,x+s,fy-ht,.1,col,3);}g.restore();}
  function ice(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();g.fillStyle='rgba('+col+',.09)';for(var i=0;i<9;i++){var x=worldX(loc,.04+i*.115,cam);if(x<-80||x>w+80)continue;var ht=55+(i%4)*25;g.beginPath();g.moveTo(x-35,fy);g.lineTo(x,fy-ht);g.lineTo(x+42,fy);g.closePath();g.fill();line(x,fy-ht,x+4,fy-8,.08,col,2);}g.restore();}
  function pyramid(loc,cam,w,h,col){var fy=floorY(loc,cam),x=worldX(loc,.72,cam);if(!onScreen(x,fy,w,h,240))return;g.save();g.fillStyle='rgba('+col+',.085)';g.beginPath();g.moveTo(x,fy-150);g.lineTo(x+160,fy);g.lineTo(x-160,fy);g.closePath();g.fill();line(x,fy-150,x,fy,.075,col,2);g.restore();}
  function bones(loc,cam,w,h,col){var fy=floorY(loc,cam),x=worldX(loc,.76,cam);if(!onScreen(x,fy,w,h,200))return;g.save();g.strokeStyle='rgba('+col+',.10)';g.lineWidth=8;g.beginPath();g.arc(x,fy-16,72,Math.PI,Math.PI*2);g.stroke();for(var i=0;i<7;i++)line(x-60+i*20,fy-20,x-66+i*20,fy+8,.085,col,4);g.restore();}
  function peaks(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();g.fillStyle='rgba('+col+',.075)';for(var i=0;i<5;i++){var x=worldX(loc,.03+i*.23,cam),ht=180+(i%3)*80;if(x<-260||x>w+260)continue;g.beginPath();g.moveTo(x-150,fy);g.lineTo(x,fy-ht);g.lineTo(x+170,fy);g.closePath();g.fill();}g.restore();}
  function clouds(loc,cam,w,h,t,col){g.save();g.fillStyle='rgba('+col+',.055)';for(var i=0;i<8;i++){var wx=(i*.18+.04)*loc.worldWidth+(t*.008*(1+(i%3)*.18));wx=((wx%(loc.worldWidth+320))+(loc.worldWidth+320))%(loc.worldWidth+320)-160;var x=wx-cam.x,y=(40+(i%3)*70)-cam.y*.12;if(x<-160||x>w+160)continue;g.beginPath();g.arc(x,y,50,0,Math.PI*2);g.arc(x+44,y+8,38,0,Math.PI*2);g.arc(x-38,y+12,32,0,Math.PI*2);g.fill();}g.restore();}
  function torii(loc,cam,w,h,col){var fy=floorY(loc,cam),x=worldX(loc,.78,cam);if(!onScreen(x,fy,w,h,150))return;line(x-48,fy-110,x-48,fy,.14,col,7);line(x+48,fy-110,x+48,fy,.14,col,7);line(x-76,fy-124,x+76,fy-124,.16,col,9);line(x-62,fy-106,x+62,fy-106,.1,col,5);}
  function rig(loc,cam,w,h,col){var fy=floorY(loc,cam),x=worldX(loc,.74,cam);if(!onScreen(x,fy,w,h,190))return;line(x,fy-210,x,fy,.11,col,7);line(x+70,fy-210,x+70,fy,.11,col,7);line(x-25,fy-210,x+95,fy-210,.11,col,9);for(var i=0;i<4;i++)line(x,fy-190+i*45,x+70,fy-145+i*45,.07,col,2);}
  function crates(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();g.strokeStyle='rgba('+col+',.09)';g.lineWidth=3;for(var i=0;i<8;i++){var x=worldX(loc,.55+(i%4)*.06,cam),y=fy-40-Math.floor(i/4)*44;if(!onScreen(x,y,w,h,80))continue;g.strokeRect(x,y,46,38);line(x,y,x+46,y+38,.055,col,2);line(x+46,y,x,y+38,.055,col,2);}g.restore();}
  function cave(loc,cam,w,h,col){var roof=-cam.y;g.save();g.fillStyle='rgba('+col+',.085)';for(var i=0;i<16;i++){var x=worldX(loc,.02+i*.067,cam);if(x<-40||x>w+40)continue;var len=45+(i%5)*22;g.beginPath();g.moveTo(x-14,roof);g.lineTo(x+16,roof);g.lineTo(x,roof+len);g.closePath();g.fill();}g.restore();}
  function alien(loc,cam,w,h,t,col){var fy=floorY(loc,cam);g.save();var moonX=worldX(loc,.76,cam),moonY=110-cam.y*.10;if(moonX>-100&&moonX<w+100){g.fillStyle='rgba('+col+',.095)';g.beginPath();g.arc(moonX,moonY,58,0,Math.PI*2);g.fill();}for(var i=0;i<8;i++){var x=worldX(loc,.08+i*.12,cam),base=fy;if(x<-70||x>w+70)continue;var tip=base-115-(i%3)*24,sw=Math.sin(t*.001+i)*5;line(x,base,x+sw,tip,.09,col,5);g.fillStyle='rgba('+col+',.075)';g.beginPath();g.arc(x+sw+5,tip-8,12,0,Math.PI*2);g.fill();}g.restore();}
  function vines(loc,cam,w,h,t,col){var roof=-cam.y;g.save();g.strokeStyle='rgba('+col+',.10)';g.lineWidth=5;for(var i=0;i<16;i++){var x=worldX(loc,.025+i*.065,cam);if(x<-40||x>w+40)continue;var len=100+(i%5)*30;g.beginPath();g.moveTo(x,roof);for(var yy=0;yy<len;yy+=22)g.lineTo(x+Math.sin(t*.001+yy*.025+i)*9,roof+yy);g.stroke();}g.restore();}
  function ruins(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();g.fillStyle='rgba('+col+',.07)';for(var i=0;i<7;i++){var x=worldX(loc,.08+i*.15,cam),ht=85+(i%3)*35;if(x<-80||x>w+80)continue;g.fillRect(x,fy-ht,25,ht);g.fillRect(x-12,fy-ht-12,49,13);}g.restore();}
  function machinery(loc,cam,w,h,t,col){var fy=floorY(loc,cam);g.save();g.strokeStyle='rgba('+col+',.08)';g.lineWidth=4;for(var i=0;i<4;i++){var x=worldX(loc,.62+i*.08,cam),y=fy-42;if(x<-60||x>w+60)continue;g.beginPath();g.arc(x,y,22+i*3,0,Math.PI*2);g.stroke();var rot=t*.0004*(i%2?-1:1);for(var a=0;a<8;a++){var aa=a*Math.PI/4+rot;line(x,y,x+Math.cos(aa)*31,y+Math.sin(aa)*31,.055,col,3);}}g.restore();}
  function pirate(loc,cam,w,h,col){var fy=floorY(loc,cam),x=worldX(loc,.68,cam);if(!onScreen(x,fy,w,h,180))return;line(x,fy-180,x,fy,.1,col,7);line(x,fy-160,x+80,fy-135,.09,col,4);g.fillStyle='rgba('+col+',.065)';g.beginPath();g.moveTo(x,fy-155);g.lineTo(x+70,fy-132);g.lineTo(x,fy-95);g.closePath();g.fill();}
  function backrooms(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();for(var i=0;i<12;i++){var x=worldX(loc,.03+i*.09,cam);if(x<-40||x>w+40)continue;g.fillStyle='rgba('+col+',.055)';g.fillRect(x,fy-240,16,240);g.fillRect(x-18,fy-240,52,10);}g.restore();}
  function trench(loc,cam,w,h,col){var fy=floorY(loc,cam);g.save();g.fillStyle='rgba('+col+',.08)';for(var i=0;i<7;i++){var x=worldX(loc,.05+i*.16,cam);if(x<-140||x>w+140)continue;var ht=90+(i%4)*55;g.beginPath();g.moveTo(x-90,fy);g.lineTo(x-20,fy-ht);g.lineTo(x+15,fy-ht*.7);g.lineTo(x+90,fy);g.closePath();g.fill();}g.restore();}

  function scene(run,state,cam,w,h,t){var loc=run.loc||D.LOCATIONS[run.area];switch(run.area){
    case'coral':coral(loc,cam,w,h,t,'255,145,120');break;case'river':reeds(loc,cam,w,h,t,'120,220,145');break;case'forest':vines(loc,cam,w,h,t,'100,210,120');break;case'secretcave':cave(loc,cam,w,h,'165,150,220');break;
    case'kelp':kelp(loc,cam,w,h,t,'70,190,150');break;case'arctic':ice(loc,cam,w,h,'215,245,255');break;case'desert':pyramid(loc,cam,w,h,'240,205,125');break;case'opensea':trench(loc,cam,w,h,'80,145,190');break;
    case'ancient':ruins(loc,cam,w,h,'190,150,90');break;case'prism':coral(loc,cam,w,h,t,'255,130,220');break;case'swamp':reeds(loc,cam,w,h,t,'150,165,80');break;case'boneyard':bones(loc,cam,w,h,'220,225,220');break;
    case'storm':clouds(loc,cam,w,h,t,'145,160,195');break;case'mountain':peaks(loc,cam,w,h,'190,215,235');break;case'olympus':ruins(loc,cam,w,h,'255,225,145');clouds(loc,cam,w,h,t,'235,245,255');break;
    case'jungle':vines(loc,cam,w,h,t,'80,195,90');break;case'alien':alien(loc,cam,w,h,t,'175,110,245');break;case'grotto':ruins(loc,cam,w,h,'110,230,235');break;case'ashen':peaks(loc,cam,w,h,'210,85,45');break;
    case'pirate':pirate(loc,cam,w,h,'190,150,80');break;case'backrooms':backrooms(loc,cam,w,h,'210,195,80');break;case'japan':torii(loc,cam,w,h,'235,85,105');break;case'oilrig':rig(loc,cam,w,h,'175,155,105');machinery(loc,cam,w,h,t,'175,155,105');break;
    case'flooded':crates(loc,cam,w,h,'110,155,145');break;case'cave':cave(loc,cam,w,h,'125,145,190');break;case'cloud':clouds(loc,cam,w,h,t,'235,245,255');break;case'trench':trench(loc,cam,w,h,'70,95,130');break;case'sanctuary':ruins(loc,cam,w,h,'145,240,205');break;
  }}
  function frame(t){size();var w=stage.clientWidth||innerWidth,h=stage.clientHeight||innerHeight;g.clearRect(0,0,w,h);var api=window.DEEPSEA,run=api&&api.run?api.run():null,state=api&&api.state?api.state():null;if(run&&run.area&&run.diver){var cam=camera(run,state,w,h);g.save();scene(run,state,cam,w,h,t);g.restore();}requestAnimationFrame(frame);}
  addEventListener('resize',size,{passive:true});size();requestAnimationFrame(frame);
})();